"""
proxy_view.py
─────────────
Turns a parsed GameState (+ the client-side shadow) into the JSON view-model
the UI consumes. Also hosts the card Counter (deck-tracking) — a stub here,
filled in at milestone M4.

Imported by runtime.start_consumer after proxy/ is on sys.path, so the
top-level `import shadow_state` resolves to the same singleton the addon uses.
"""
import json
import sys
from pathlib import Path

import shadow_state
# R28: optional local BattleLog.json fallback for HP / tipo / maxTipo.
# The wire doesn't carry these as direct integers; the game client writes
# them to a JSON file we can tail. Best-effort import — if the module fails
# to load we just skip the override.
try:
    import battle_log as _battle_log
except Exception:
    _battle_log = None

# Fate id → yi-sim talent metadata (generated by build_fate_map.py).
_FATE_MAP_PATH = Path(__file__).resolve().parent / "proxy" / "fate_talent_map.json"
_fate_map_cache = None
_unmapped_warned: set = set()


def _fate_map() -> dict:
    global _fate_map_cache
    if _fate_map_cache is None:
        try:
            _fate_map_cache = json.loads(_FATE_MAP_PATH.read_text(encoding="utf-8"))
        except Exception:
            _fate_map_cache = {}
    return _fate_map_cache


def _resolve_fate_meta(fmap: dict, fid: int, phase: int):
    """Look up a fate's talent metadata, picking the right phase variant.

    Backward-compat: today every fate_talent_map.json entry is single-variant
    (phase-agnostic). If a future entry adds `phases: {"1": {...}, "2": {...}}`,
    we merge the matching phase's overrides over the base entry. If the entry
    has no `phases` key the base entry is returned unchanged.
    Returns None when the id is unmapped.
    """
    base = fmap.get(str(fid))
    if not base:
        return None
    phases = base.get("phases") if isinstance(base, dict) else None
    if not isinstance(phases, dict):
        return base
    override = phases.get(str(phase)) or phases.get(int(phase) if isinstance(phase, int) else None)
    if isinstance(override, dict):
        merged = dict(base)
        merged.update(override)
        # `phases` itself isn't useful downstream — drop it.
        merged.pop("phases", None)
        return merged
    return base


def _warn_unmapped_fate(fid: int) -> None:
    """Log a one-shot warning (per process) when a fate id is missing from the
    talent map. The fate still surfaces in `fateNames` for display — we just
    can't model it in the damage sim yet."""
    if fid in _unmapped_warned:
        return
    _unmapped_warned.add(fid)
    try:
        name = shadow_state.fate_name(fid)
    except Exception:
        name = "?"
    print(f"[fate] unmapped id={fid} ({name}) — add to fate_talent_map.json to model in sim",
          file=sys.stderr, flush=True)


_derivation_map_cache: dict | None = None


def _derivation_name(did: int) -> str:
    """Look up the Chinese name for a derivation id from
    tools/derivations_game.json. Returns '#<id>' if unknown."""
    global _derivation_map_cache
    if _derivation_map_cache is None:
        from pathlib import Path
        import json as _json
        try:
            root = Path(__file__).resolve().parent
            path = root / "tools" / "derivations_game.json"
            if not path.exists():
                # Fallback path when proxy/ is the cwd parent
                path = root.parent / "tools" / "derivations_game.json"
            data = _json.loads(path.read_text(encoding="utf-8"))
            _derivation_map_cache = {
                int(e["id"]): (e.get("name_cn") or e.get("name_en") or "")
                for e in data.get("entries", []) if e.get("id") is not None
            }
        except Exception:
            _derivation_map_cache = {}
    return _derivation_map_cache.get(int(did)) or f"#{did}"


def _fates_to_talents(fate_ids):
    """Convert a list of fate ids (in PICK ORDER) into (talents, names).

    Each entry's index in the list = phase (1-indexed). The phase is stored
    both as the existing `position` field (yisim uses it to resolve any
    `{n}` placeholder in `runtimeKey`) AND as a new `phase` field on the
    talent object so the UI and any future phase-aware lookup can use it.
    Unmapped ids still surface in `names` but are skipped in `talents`,
    and a one-shot console warning fires per unique unmapped id.

    talents match the shape yisim.simulate expects via normalizeTalents:
      {detected, position, phase, name, simulationKind, runtimeKey,
       grantedCardBaseIds}

    Phase variants seam: if a future fate_talent_map.json entry adds
    `phases: { "2": { ... }, "3": { ... } }`, `_resolve_fate_meta` will
    apply the right override automatically — no caller change needed.
    """
    fmap = _fate_map()
    talents, names = [], []
    for i, fid in enumerate(fate_ids or []):
        try:
            fid_i = int(fid)
        except (TypeError, ValueError):
            continue
        phase = i + 1
        names.append(shadow_state.fate_name(fid_i))
        meta = _resolve_fate_meta(fmap, fid_i, phase)
        if not meta:
            _warn_unmapped_fate(fid_i)
            continue
        talents.append({
            "detected": True,
            "position": phase,
            "phase": phase,
            "name": meta.get("name", ""),
            "simulationKind": meta.get("simulationKind", "non-combat-or-unsupported"),
            "runtimeKey": meta.get("runtimeKey"),
            "grantedCardBaseIds": meta.get("grantedCardBaseIds") or [],
        })
    return talents, names


def _build_fates():
    """Back-compat shim: ME's fates from addon.chosen_fates → (talents, names)."""
    try:
        import addon
        ids = list(addon.chosen_fates)
    except Exception:
        ids = []
    return _fates_to_talents(ids)


def _card(c):
    """ZoneCard | CardState | None → {name, level, id} | None."""
    if c is None:
        return None
    return {"name": getattr(c, "name", "?"), "level": int(getattr(c, "level", 1) or 1),
            "id": getattr(c, "id", None)}


def _signed64(v):
    """Wire uint64 → signed (extraMaxHp can be negative, e.g. -5 == 2^64-5)."""
    v = int(v or 0)
    return v - (1 << 64) if v >= (1 << 63) else v


def _oracle_side(ps, board_dicts, unlocked=8, is_me=False):
    """Build the Yi Xian Oracle fixture-player fields for one side from its live
    PlayerState (+ the view-model board dicts, which carry card ids). These are
    the SAME fields the recorded round-stat carries, read off the wire:
      characterId = publicData[12], realm = realm_tier, extraMaxHp = publicData[4],
      talents = the f200[5]/[13] list (PlayerState.fates), fateStrategies = f200[16].
    `unlocked` = this round's usable board-slot count (matters for cards that scale
    with empty slots, e.g. 逍遥无影拳). `is_me` enables the career lookup, which is
    only tracked for the local player (the opponent's class isn't on the wire).
    Returns None if there's no usable identity (so callers can skip the Oracle)."""
    if ps is None:
        return None
    raw = getattr(ps, "raw", None) or {}
    f200 = raw.get("200") or raw.get("200-1") or {}
    if not isinstance(f200, dict):
        f200 = {}
    fate_strats = []
    fb = f200.get("16")
    if isinstance(fb, (bytes, bytearray)) and fb:
        try:
            fate_strats = [int(x) for x in shadow_state.decode_varint_list(bytes(fb))]
        except Exception:
            fate_strats = []
    used = [int(c["id"]) if (c and c.get("id")) else 0 for c in (board_dicts or [])]
    char_id = int(raw.get("12") or 0)
    # career (副职/class) is the in-game pick — tracked only for the local player;
    # the opponent's isn't broadcast, so it stays 0 (best-effort). sect is the
    # school, derivable exactly from the character id (verified: sect == cid//1e6).
    career = 0
    if is_me:
        try:
            career = int(shadow_state.get_career_pick() or 0)
        except Exception:
            career = 0
    return {
        "characterId": char_id,
        "level": int(getattr(ps, "realm_tier", 1) or 1),
        # exp == cultivation (修为): the Oracle reads characterUI.exp as cultivation
        # for cultivation-scaling cards. Sourced from the wire-parsed xiuwei.
        "exp": int(getattr(ps, "xiuwei", 0) or 0),
        "extraMaxHp": _signed64(raw.get("4")),
        "talents": [int(t) for t in (getattr(ps, "fates", []) or [])],
        "fateStrategies": fate_strats,
        "usedCards": used,
        # Previously hardcoded (8/0/0/100); these are all available live and lift
        # the matchup's winner accuracy. life = the destiny (命) pool.
        "unlockGrids": int(unlocked or 8),
        "sect": char_id // 1000000 if char_id else 0,
        "career": career,
        "life": int(getattr(ps, "destiny", 100) or 100),
    }


def _board_list(board, unlocked):
    out = []
    for i in range(shadow_state.BOARD_SLOTS):
        c = board[i] if board and i < len(board) else None
        out.append(_card(c))
    return out


class OpponentTracker:
    """Remembers each player's board per round so the matchup can use the
    opponent's board from a PREVIOUS round — in-game you never see an
    opponent's current-round board, only what they last fought with.
    """

    def __init__(self):
        self.reset()

    def reset(self):
        self._by_round = {}   # round_num -> {player_id: [card-dict|None, ...]}

    def observe(self, state):
        r = state.round_num
        slot = self._by_round.setdefault(r, {})
        for p in state.players:
            slot[p.player_id] = [_card(c) for c in (p.board or [])]
        # Keep memory bounded.
        if len(self._by_round) > 4:
            for old in sorted(self._by_round)[:-4]:
                self._by_round.pop(old, None)

    def last_seen(self, player_id, current_round):
        """The opponent's board from the most recent round before this one.
        Returns (board, from_round) or (None, None)."""
        rounds = sorted(rr for rr in self._by_round if rr < current_round)
        for rr in reversed(rounds):
            board = self._by_round[rr].get(player_id)
            if board and any(board):
                return board, rr
        return None, None

    def previous_round(self, player_id, current_round):
        """The opponent's board strictly from `current_round - 1`.

        Use this for the matchup panel — "what the current opponent had last
        round" — instead of `last_seen`, which can drift many rounds back if
        the opponent has been quiet. Falls back to `last_seen` if the previous
        round is missing (e.g. very first round we observed them).
        """
        slot = self._by_round.get(current_round - 1, {})
        board = slot.get(player_id)
        if board and any(board):
            return board, current_round - 1
        return self.last_seen(player_id, current_round)


def _pick_opponent(state):
    """Choose the opponent to display/simulate against.

    Preference order:
      1. **The next-round opponent** — `state.players[me].next_opponent_id` (the
         UID broadcast on the user's player struct, field 9). YiXianPai pairs you
         with a DIFFERENT opponent each round, so this is what the user is about
         to fight; not the same as the previously-fought opponent.
      2. The player the user most recently fought (`addon.my_last_opponent`)
         — fallback for round 1 / states where field 9 was missing.
      3. The live opponent with the most cards on board.
      4. The first non-me player.
    Returns a PlayerState or None.
    """
    if not state.players:
        return None
    me_idx = state.me_index
    others = [(i, p) for i, p in enumerate(state.players) if i != me_idx]
    if not others:
        return None

    # 1. Next-round matchup from the broadcast.
    next_uid = ""
    if 0 <= me_idx < len(state.players):
        next_uid = getattr(state.players[me_idx], "next_opponent_id", "") or ""
    if next_uid:
        for _, p in others:
            if p.player_id == next_uid:
                return p

    # 2. Fallback: most recently fought opponent (`my_last_opponent`).
    try:
        import addon
        target_uid = addon.my_last_opponent
    except Exception:
        target_uid = ""
    if target_uid:
        for _, p in others:
            if p.player_id == target_uid and p.destiny > 0:
                return p
    # Most board cards among still-alive opponents.
    alive = [(i, p) for i, p in others if p.destiny > 0] or others
    alive.sort(key=lambda ip: sum(1 for c in (ip[1].board or []) if c), reverse=True)
    return alive[0][1]


# ─── HP formula (predicted fallback when BattleLog.json is unavailable) ──────
#
# The wire doesn't carry HP. BattleLog.json is the authoritative source but
# only updates when the game flushes per-round entries, and isn't available
# at all for the current opponent until that round's battle is recorded.
# When BL is missing for a round we use this empirical formula:
#
#     HP = realm_base[realm] + (round_num - 1) * 2
#
# where realm_base = {1: 40, 2: 45, 3: 52, 4: 62, 5: 75} — the cumulative
# breakthrough HP totals (+5, +7, +10, +13 per breakthrough). The +2/round
# baseline grows with xiuwei progression. Verified exact-match for at least
# one full game; drifts under-count by ~0–10 HP late-game when the player
# picks max_hp-boost cards (锻髓, 大还丹, etc.) — those effects are not on
# the wire and would require simulating each card's per-turn rule.
#
# Always paired with a `predicted=True` flag so the UI can mark these values
# visually distinct from authoritative BL values.
_REALM_BASE_HP = {1: 40, 2: 45, 3: 52, 4: 62, 5: 75}


def _predict_hp(round_num: int, realm_tier: int) -> int:
    """Predict max_hp from realm + round. Returns 0 if inputs invalid."""
    if not (isinstance(round_num, int) and round_num >= 1):
        return 0
    base = _REALM_BASE_HP.get(realm_tier or 1)
    if base is None:
        return 0
    return base + (round_num - 1) * 2


def _battle_log_stats(round_num: int, display_name: str):
    """Look up `(life, xiuwei, tipo, max_tipo, max_hp, realm_tier,
    from_round)` from BattleLog.json for the given player display name.

    Returns None if the log isn't available, the module didn't import, the
    display name is missing, or no entry exists. The log is the only
    authoritative source for `max_hp`, `tipo`, and `max_tipo` — the wire
    protocol doesn't carry them directly. Callers should fall back to
    wire-derived values when this returns None.
    """
    if _battle_log is None or not display_name:
        return None
    try:
        return _battle_log.get_reader().extract_stats(round_num, display_name)
    except Exception:
        return None


def build_view_model(state, counter=None, last_battle=None, opp_tracker=None):
    sh = shadow_state.shadow
    unlocked = shadow_state.unlocked_board_slots(state.round_num)

    vm = {
        "round": state.round_num,
        "phase": state.phase,
        "me": None,
        "opponent": None,
        "counter": {"remaining": counter.remaining() if counter else {}},
    }

    # ── You ──────────────────────────────────────────────────────────────────
    if state.me_index >= 0 and state.me_index < len(state.players):
        me = state.players[state.me_index]
        # 灵羽 merge: lv2/3 灵羽 placed on the board merges into a lv1 qi/agility
        # target at battle-time (server-side, no wire signal). Substitute before
        # building the view-model so the UI/damage sim see the merged result.
        # Any 灵羽 lv2/3 that finds NO valid target stays as 灵羽 and is logged
        # in `lingyu_unresolved` so the damage panel can show "unidentified card".
        lingyu_unresolved = []
        if sh is not None:
            from lingyu_merge import resolve_lingyu_merges
            merged_board, lingyu_unresolved = resolve_lingyu_merges(list(sh.board))
            hand = [_card(c) for c in sh.hand if c is not None]
            board = _board_list(merged_board, unlocked)
            xiuwei, tipo, realm = sh.xiuwei, sh.tipo, sh.realm_tier
            rerolls = sh.rerolls
            seasonal = [_card(c) for c in sh.seasonal.values() if c is not None]
        else:
            from lingyu_merge import resolve_lingyu_merges
            merged_board, lingyu_unresolved = resolve_lingyu_merges(list(me.board or []))
            hand = [_card(c) for c in me.cards]
            board = _board_list(merged_board, unlocked)
            xiuwei, tipo, realm = me.xiuwei, me.tipo, me.realm_tier
            rerolls = getattr(me, "rerolls", 0)
            seasonal = []
        # HP / tipo / maxTipo prefer battle_log.json (authoritative). When BL
        # doesn't have a record for this round we fall back to the formula
        # `realm_base[realm] + (R-1)*2` and flag the value as `hpIsPredicted`
        # so the UI can render it visually distinct from authoritative values.
        # The wire does NOT carry HP directly.
        log_stats = _battle_log_stats(state.round_num, getattr(me, "display_name", ""))
        log_hp     = int(log_stats["max_hp"])     if log_stats else 0
        log_tipo   = int(log_stats["tipo"])       if log_stats else None
        log_maxtp  = int(log_stats["max_tipo"])   if log_stats else 0
        log_round  = int(log_stats["from_round"]) if log_stats else None

        hp_is_predicted = (log_hp <= 0)
        if hp_is_predicted:
            hp_val = _predict_hp(state.round_num, realm)
        else:
            hp_val = log_hp
        tipo_val = log_tipo if log_tipo is not None else tipo
        max_tipo = log_maxtp  # 0 if log missing — UI treats 0 as "unknown"

        avail, thr, gate = shadow_state.breakthrough_status(realm, xiuwei, tipo_val)
        fates, fate_names = _build_fates()
        # Derivations (天衍) — display-only, picked via SimpleClientPact code=47.
        # Names are looked up from tools/derivations_game.json keyed by id.
        try:
            import addon as _addon
            derivation_ids = list(getattr(_addon, "chosen_derivations", []) or [])
        except Exception:
            derivation_ids = []
        derivation_names = [_derivation_name(did) for did in derivation_ids]
        # Annotate every hand card with how many copies are left in the deck
        # so the deck_tracker.jsonl debug dump shows them inline. `remaining()`
        # is keyed by canonical name (handles paired transform cards).
        remaining_map = counter.remaining() if counter else {}
        for hc in hand:
            if isinstance(hc, dict):
                canon = _canonical(hc.get("name", ""))
                hc["copiesLeftInDeck"] = remaining_map.get(canon)
                # Canonical key into counter.remaining, so the counter window
                # can pin / filter the rows for cards currently in hand.
                hc["counterKey"] = canon
        vm["me"] = {
            "destiny": me.destiny, "hp": hp_val,
            "hpIsPredicted": hp_is_predicted,
            "hpFromLog": log_hp,
            "tipoFromLog": (log_tipo if log_tipo is not None else 0),
            "maxTipoFromLog": log_maxtp,
            "logFromRound": log_round,
            "xiuwei": xiuwei, "tipo": tipo_val, "max_tipo": max_tipo,
            "realm_tier": realm,
            "rerolls": rerolls,
            "unlocked": unlocked,
            "hand": hand, "board": board,
            "seasonal": seasonal,
            "fates": fates, "fateNames": fate_names,
            "derivations": derivation_ids,
            "derivationNames": derivation_names,
            "breakthrough": {"available": bool(avail), "threshold": thr, "gate": gate},
            # Slot indices where a 灵羽 lv2/3 found no eligible lv1 target. When
            # non-empty, the UI shows "未识别卡片 — 伤害计算不可用" instead of
            # damage numbers (yisim has no 灵羽 implementation).
            "lingyuUnresolved": lingyu_unresolved,
            # Yi Xian Oracle fixture-player fields (ids the real engine consumes).
            "oracle": _oracle_side(state.players[state.me_index] if state.me_index >= 0 else None,
                                   board, unlocked=unlocked, is_me=True),
        }
        # _oracle_side reads cultivation/realm off the wire PlayerState, which is the
        # ROUND-START value. The shadow (sh) is current — it tracks this round's
        # absorbs (+1 修为 each) and breakthroughs. Sync the fixture to the CURRENT
        # values so the calc uses my real cultivation/realm, not last round's.
        if vm["me"].get("oracle"):
            vm["me"]["oracle"]["exp"] = int(xiuwei or 0)
            vm["me"]["oracle"]["level"] = int(realm or 1)

    # ── Opponent (matchup target) ──────────────────────────────────────────────
    # Round 14: use opp.board DIRECTLY — it's the current-round board, parsed
    # from f200.6 on each player struct in the latest GameStatus. The server
    # broadcasts every player's board at the start of each round; that's the
    # roster the opponent will fight us with this round (boards lock between
    # rounds). OpponentTracker still observes for history, but we don't pull
    # the displayed board from it anymore.
    opp = _pick_opponent(state)
    if opp is not None:
        board = [_card(c) for c in (opp.board or [])]
        from_round = state.round_num
        # Pad/truncate to 8 slots.
        board = (board + [None] * shadow_state.BOARD_SLOTS)[:shadow_state.BOARD_SLOTS]
        # R26: opponent fates decoded from f200["5"] (packed varint list, R24
        # Phase B addendum 8) flow through the SAME pipeline as me's fates —
        # `_fates_to_talents` builds talent objects with `phase = pick order`
        # so the matchup-mode sim can apply them via opts.opponentTalents.
        opp_fates, opp_fate_names = _fates_to_talents(getattr(opp, "fates", []) or [])
        # R28: BattleLog override for opponent too (same precedence as ME).
        opp_log = _battle_log_stats(state.round_num, getattr(opp, "display_name", ""))
        opp_log_hp    = int(opp_log["max_hp"])     if opp_log else 0
        opp_log_tipo  = int(opp_log["tipo"])       if opp_log else None
        opp_log_maxtp = int(opp_log["max_tipo"])   if opp_log else 0
        # Opponent HP: prefer BattleLog, fall back to formula prediction.
        # The wire doesn't carry HP for any player. When the formula is used,
        # `hpIsPredicted` is True so the UI can render the chip differently.
        opp_hp_predicted = (opp_log_hp <= 0)
        if opp_hp_predicted:
            opp_hp_val = _predict_hp(state.round_num, opp.realm_tier)
        else:
            opp_hp_val = opp_log_hp
        opp_tipo_val = opp_log_tipo if opp_log_tipo is not None else opp.tipo
        vm["opponent"] = {
            "player_id": opp.player_id,
            "character": "",  # opponents' class isn't directly exposed
            "destiny": opp.destiny, "hp": opp_hp_val,
            "hpIsPredicted": opp_hp_predicted,
            "hpFromLog": opp_log_hp,
            "tipoFromLog": (opp_log_tipo if opp_log_tipo is not None else 0),
            "maxTipoFromLog": opp_log_maxtp,
            "xiuwei": opp.xiuwei, "tipo": opp_tipo_val, "max_tipo": opp_log_maxtp,
            "realm_tier": opp.realm_tier,
            "phase": state.phase,
            "unlocked": unlocked,
            "board": board,
            "boardFromRound": from_round,
            "fates": opp_fates, "fateNames": opp_fate_names,
            "oracle": _oracle_side(opp, board, unlocked=unlocked, is_me=False),
        }

    # R27: one-shot per-frame console probe so the user can read both
    # candidates without opening devtools. Prints ME plus every visible
    # player at GameStatus arrival — gated to `prep` to avoid duplicate
    # log lines during the battle phase.
    if state.phase == "prep":
        _hp_probe(state)

    return vm


_hp_probe_seen: set = set()


def _hp_probe(state) -> None:
    """Print per-player `(xiuwei, hp_field)` plus the BattleLog HP (the only
    authoritative source) once per (round, me-uid) pair. Diagnostic only.
    """
    me_uid = ""
    if 0 <= state.me_index < len(state.players):
        me_uid = state.players[state.me_index].player_id
    key = (state.round_num, me_uid)
    if key in _hp_probe_seen:
        return
    _hp_probe_seen.add(key)
    import sys
    for p in state.players:
        tag = "ME " if p.player_id == me_uid else "   "
        f5 = int(getattr(p, "hp_field", 0) or 0)
        log = _battle_log_stats(state.round_num, getattr(p, "display_name", ""))
        log_hp = int(log["max_hp"]) if log else 0
        print(f"[hp-probe] R{state.round_num} {tag}{p.player_id[:24]:24s} "
              f"xiuwei={p.xiuwei:3d} field5={f5:3d}  "
              f"hp(log)={log_hp:3d}",
              file=sys.stderr, flush=True)


DEFAULT_COPIES = 8  # each card has 8 copies in the deck unless specified
PHASE5_COPIES = 6   # phase-5 (latest-patch) cards: 6 copies instead of 8

# Cards with non-default deck size. Add new entries here as we learn them.
# Note: the reduced-count dans (洗髓丹/悟道丹/锻体玄丹) are managed by the
# sidejob-pool system via SIDEJOB_BONUSES selection_overrides when the player
# picks 炼丹师. SPECIAL_COPIES stays for any future non-sidejob cards with
# custom deck sizes.
SPECIAL_COPIES: dict[str, int] = {}


# ─── Sidejob (副职) tracking ──────────────────────────────────────────────────
# The wire's SelectCareerReq carries career_id 1..7 — a compact enum just for
# the wire. The CardConfig sect/class enum has a wider 0..12 range used for
# the card ID prefix (id // 1_000_000). Map between the two:
CAREER_TO_SIDEJOB_PREFIX = {
    1: 2,    # 炼丹师 Elixirist
    2: 3,    # 符咒师 Talisman
    3: 5,    # 琴师   Musician
    4: 6,    # 画师   Painter
    5: 8,    # 阵法师 Formation
    6: 9,    # 灵植师 Plant
    7: 11,   # 命理师 Diviner
}
SIDEJOB_PREFIXES = set(CAREER_TO_SIDEJOB_PREFIX.values())

# Per-sidejob deck-pool rules. At sidejob selection, EVERY card belonging to
# the picked sidejob is added to the pool at the default count (DEFAULT_COPIES
# or PHASE5_COPIES for phase-5 cards). Two kinds of per-sidejob exceptions:
#
#   'selection_overrides'  — at selection, these cards get the override count
#                            instead of the default (e.g. 洗髓丹 = 3, not 8).
#                            Cards NOT in this dict use the default.
#   'realm_N_to_M'         — extra copies ADDED on top of the existing pool
#                            when the player crosses realm tier N→M.
#
# Sidejobs without an entry below get the default 8 / 6 for every card with
# no overrides and no breakthrough bonuses.
SIDEJOB_BONUSES: dict[int, dict[str, dict[str, int]]] = {
    2: {  # 炼丹师 Elixirist
        # Elixir now behaves like every other sidejob: all cards at the phase
        # default (8, or 6 for phase-5) with only these per-card overrides — no
        # realm-tier breakthrough bonuses (the old realm_3_to_4 / realm_4_to_5
        # extra dans were removed).
        "selection_overrides": {
            "洗髓丹":     3,   # 修为丹 ([炼化]→+修为), phase 4 — 3 not 8
            "悟道丹":     3,   # phase 5 — 3 not 6
            "锻体玄丹":   3,   # phase 5 — 3 not 6
            "冰灵护体丹": 6,   # phase 5 — 6 (= phase-5 default; explicit)
        },
    },
    # 符咒师 / 琴师 / 画师 / 阵法师 / 灵植师 / 命理师: no per-card overrides,
    # no breakthrough bonuses — every card defaults to 8 (or 6 if phase 5).
}


# Lazy-load: card-name → ID prefix lookup (from tools/card_phases.json's keys
# which are the numeric card ids). Used to identify sidejob cards.
_SIDEJOB_PREFIX_CACHE: dict | None = None

# Lazy-load: set of card names that are "personal" — granted by fates or
# other one-shot sources, NOT drawn from any sect/sidejob deck. Identified
# by card id < 1_000_000 in tools/card_phases.json. Examples: 云泉道茶 (fate
# grant), 狂剑·炎舞 (fate grant), 不动金刚阵 (special card). These have no
# deck copy count and must be excluded from the counter entirely.
_PERSONAL_CARD_NAMES_CACHE: set | None = None


def _personal_card_names() -> set:
    """Return the set of canonical card names that are personal/fate-granted
    (appear ONLY with card id < 1_000_000 in card_phases.json) — these have
    no deck copies and should never appear in the Counter's remaining list.

    Many sidejob cards (e.g. 符咒师's 奔雷符) have a TWIN entry in the same
    json with id < 1000 — these twins are e.g. fate-preview variants. A name
    is personal only when NO id-variant of it is >= 1_000_000, otherwise the
    sidejob/sect deck version owns the name and it must remain visible."""
    global _PERSONAL_CARD_NAMES_CACHE
    if _PERSONAL_CARD_NAMES_CACHE is not None:
        return _PERSONAL_CARD_NAMES_CACHE
    low_ids: set = set()   # canonical names appearing with id < 1_000_000
    high_ids: set = set()  # canonical names appearing with id >= 1_000_000
    try:
        with _PHASE_MAP_FILE.open(encoding="utf-8") as f:
            data = json.load(f)
        for cid_str, info in data.items():
            try:
                cid = int(cid_str)
            except (TypeError, ValueError):
                continue
            nm = info.get("name", "")
            if not nm:
                continue
            key = _canonical(_normalize_sep(nm))
            if cid < 1_000_000:
                low_ids.add(key)
            else:
                high_ids.add(key)
    except Exception:
        pass
    # Personal = appears low-id only, never with a deck-card high-id variant.
    _PERSONAL_CARD_NAMES_CACHE = low_ids - high_ids
    return _PERSONAL_CARD_NAMES_CACHE


def _name_to_sidejob_prefix() -> dict:
    """Return {card_name: id_prefix} where id_prefix = cid // 1_000_000.
    Only includes cards whose prefix is in SIDEJOB_PREFIXES (i.e. side-job
    cards). Cached on first call."""
    global _SIDEJOB_PREFIX_CACHE
    if _SIDEJOB_PREFIX_CACHE is not None:
        return _SIDEJOB_PREFIX_CACHE
    out: dict[str, int] = {}
    try:
        with _PHASE_MAP_FILE.open(encoding="utf-8") as f:
            data = json.load(f)
        for cid_str, info in data.items():
            try:
                cid = int(cid_str)
            except (TypeError, ValueError):
                continue
            prefix = cid // 1_000_000
            if prefix not in SIDEJOB_PREFIXES:
                continue
            nm = info.get("name", "")
            if not nm:
                continue
            # Normalize separator (card_phases.json uses •, runtime uses ·).
            out[_normalize_sep(nm)] = prefix
    except Exception:
        out = {}
    _SIDEJOB_PREFIX_CACHE = out
    return out


# Lazy-load: per-sidejob default deck pool. {prefix: {card_name: default_count}}
# where default_count is PHASE5_COPIES for phase-5 cards, DEFAULT_COPIES
# otherwise. Used to populate the pool when the player picks a sidejob.
_SIDEJOB_DEFAULT_POOL_CACHE: dict | None = None


def _sidejob_pool_filtered(prefix: int, min_phase: int = 1) -> dict:
    """Return {canonical_name: default_count} for cards in the given sidejob
    prefix whose phase is >= `min_phase`.

    Used for 副职兼修 secondary picks: the fate only adds cards of the pick's
    phase and above, not the realm-1 starter cards. For primary picks (or
    when no filtering is desired) pass `min_phase=1` to include everything.

    Keys are CANONICAL (paired transform cards merged into one shared key).
    """
    out: dict[str, int] = {}
    try:
        with _PHASE_MAP_FILE.open(encoding="utf-8") as f:
            data = json.load(f)
        for cid_str, info in data.items():
            try:
                cid = int(cid_str)
            except (TypeError, ValueError):
                continue
            if cid // 1_000_000 != prefix:
                continue
            ph = int(info.get("phase", 0) or 0)
            if ph < min_phase:
                continue
            nm = info.get("name", "")
            if not nm:
                continue
            key = _canonical(_normalize_sep(nm))
            cnt = PHASE5_COPIES if ph == 5 else DEFAULT_COPIES
            if cnt > out.get(key, 0):
                out[key] = cnt
    except Exception:
        return {}
    return out


def _sidejob_default_pool(prefix: int) -> dict:
    """Return {card_name: default_count} for all cards in the given sidejob
    prefix (8 copies by default, 6 if phase 5).

    Keys are CANONICAL (paired transform cards like 天谕·守 / 天谕·攻 are
    merged into 天谕·攻/守 with ONE shared count) so lookups from the
    Counter — which always uses `_canonical(name)` — match correctly."""
    global _SIDEJOB_DEFAULT_POOL_CACHE
    if _SIDEJOB_DEFAULT_POOL_CACHE is None:
        all_pools: dict[int, dict[str, int]] = {}
        try:
            with _PHASE_MAP_FILE.open(encoding="utf-8") as f:
                data = json.load(f)
            for cid_str, info in data.items():
                try:
                    cid = int(cid_str)
                except (TypeError, ValueError):
                    continue
                p = cid // 1_000_000
                if p not in SIDEJOB_PREFIXES:
                    continue
                nm = info.get("name", "")
                if not nm:
                    continue
                nm = _normalize_sep(nm)
                key = _canonical(nm)  # merge paired cards into the shared key
                ph = int(info.get("phase", 0) or 0)
                cnt = PHASE5_COPIES if ph == 5 else DEFAULT_COPIES
                bucket = all_pools.setdefault(p, {})
                # max() ensures the pair's shared slot keeps a single count
                # even when both faces have the same phase/count.
                if cnt > bucket.get(key, 0):
                    bucket[key] = cnt
        except Exception:
            all_pools = {}
        _SIDEJOB_DEFAULT_POOL_CACHE = all_pools
    return dict(_SIDEJOB_DEFAULT_POOL_CACHE.get(prefix, {}))


# Lazy-load card-name → phase mapping from tools/card_phases.json (extracted
# from CardConfig.xlsx via tools/extract_card_phases.py). Used to identify
# phase-5 cards for the reroll-copies rule.
_PHASE_MAP_FILE = Path(__file__).resolve().parent / "tools" / "card_phases.json"
_phase_map_cache: dict | None = None


def _name_to_phase() -> dict:
    """Return {card_name: highest_observed_phase}. Cached.

    Some names appear under multiple ids (e.g. base + leveled forms or
    cross-references); we keep the highest phase value seen, which biases
    toward the newer / more-restrictive rule.
    """
    global _phase_map_cache
    if _phase_map_cache is not None:
        return _phase_map_cache
    out: dict[str, int] = {}
    try:
        with _PHASE_MAP_FILE.open(encoding="utf-8") as f:
            data = json.load(f)
        for info in data.values():
            nm = info.get("name", "")
            ph = int(info.get("phase", 0) or 0)
            if not nm:
                continue
            # card_phases.json uses U+2022 BULLET; runtime card names use
            # U+00B7 MIDDLE DOT. Normalize so lookups by the runtime name
            # find the right entry.
            nm = _normalize_sep(nm)
            if ph > out.get(nm, 0):
                out[nm] = ph
    except Exception:
        # Missing or unreadable file → return empty map; remaining() falls
        # back to DEFAULT_COPIES for everything (pre-phase-5 behavior).
        out = {}
    _phase_map_cache = out
    return out

# Cards exempt from the +3 reroll-burn penalty. Rerolling these away still
# costs the 1 copy that was originally drawn, but the game does NOT burn the
# extra 3 copies from the deck. (Confirmed game-rule for Painter side-job
# class spells that are part of a limited grant pool, not the regular deck.)
NO_REROLL_PENALTY = {
    "练笔",      # Sketch
    "以画入道",  # Painting as Dao
    "妙笔生花",  # Magic Brush Flowers
    "触类旁通",  # Inferring from one to others
}

# Cards whose REROLL grants a replacement that ISN'T pulled from the deck.
# When the player rerolls one of these away, the NEW card that appears in
# the slot is drawn from a special grant pool (e.g. Painter [置换] picks),
# so it does NOT consume a deck copy of itself. We skip the +1 draw
# credit for the replacement in `_drain_reroll_events`.
FREE_REPLACE_CARDS = {
    "以画入道",  # Painting as Dao
    "妙笔生花",  # Magic Brush Flowers
    "触类旁通",  # Inferring from one to others
}


# The game uses TWO different separator characters in different data sources:
#   • U+2022 BULLET            — appears in CardConfig.xlsx (tools/card_phases.json)
#   · U+00B7 MIDDLE DOT        — appears at runtime (proxy/card_id_map.json)
# Normalize to the middle dot so lookups work regardless of source.
_SEP_NORMALIZE = str.maketrans({"•": "·"})
# Reverse direction — needed by the native HUD lookup, which keys by the
# CardConfig.name spelling (sometimes using U+2022).
_SEP_DENORMALIZE = str.maketrans({"·": "•"})


def _sep_variants(name: str) -> set:
    """Every separator spelling of a card name (U+00B7 · and U+2022 •)."""
    if not isinstance(name, str) or not name:
        return set()
    return {name, name.translate(_SEP_NORMALIZE), name.translate(_SEP_DENORMALIZE)}


def _normalize_sep(name):
    """Normalize separator characters in a card name so lookups against
    PAIRED_CARDS / card_phases.json match regardless of which separator
    variant the data source happens to use."""
    if not isinstance(name, str):
        return name
    return name.translate(_SEP_NORMALIZE)


# Paired transform cards (Diviner / 命理师 class). Each pair occupies ONE
# slot in the deck — drawing or rerolling either face decrements the shared
# pool. We track them under a merged display name so the counter shows one
# row per pair with the correct shared remaining count.
# (Note: 天机·地煞 / 天机·返蛊 are unrelated regular cards from a different
# sub-class and are NOT in this map.)
# Keys and values use the middle dot (U+00B7) to match the runtime
# card_id_map.json convention.
PAIRED_CARDS = {
    "天谕·攻":   "天谕·攻/守",
    "天谕·守":   "天谕·攻/守",
    "天运·避凶": "天运·避凶/趋吉",
    "天运·趋吉": "天运·避凶/趋吉",
    "天命·飞逝": "天命·飞逝/重现",
    "天命·重现": "天命·飞逝/重现",
    "天星·牵引": "天星·牵引/御心",
    "天星·御心": "天星·牵引/御心",
    "天机·顺应": "天机·顺应/逆施",
    "天机·逆施": "天机·顺应/逆施",
}

# Reverse lookup: canonical (merged) name -> one face name. Used for phase
# lookup. Both faces in a pair share the same phase, so either face works.
_PAIR_CANONICAL_TO_FACE = {canon: face for face, canon in PAIRED_CARDS.items()}


def remaining_with_aliases(remaining) -> dict:
    """Expand a canonical `remaining` dict into every display-name form the
    in-game native HUD might look a card up by, all pointing at the same count.

    The Counter keys `remaining` canonically: paired transform cards under one
    MERGED name (天谕·攻/守) and whatever separator card_id_map.json happened to
    use (it mixes · and •). The native HUD (native_hud/csharp/Hud.cs) looks
    cards up by the live CardConfig.name — a single FACE name (天谕·攻) with
    possibly the OTHER separator spelling — via an EXACT dict match. Without
    this expansion those lookups miss and the HUD shows "剩?".

    For each (key, count): emit `key` and both separator spellings; if `key`
    is a merged pair canonical, also emit BOTH faces (and their separator
    spellings) → the same count (a pair's faces share one deck pool)."""
    out: dict = {}
    for key, count in (remaining or {}).items():
        names = _sep_variants(key)
        if key in _PAIR_CANONICAL_TO_FACE:
            for face, canon in PAIRED_CARDS.items():
                if canon == key:
                    names |= _sep_variants(face)
        for nm in names:
            out[nm] = count
    return out


def _canonical(name):
    """For paired transform cards return the merged display name, otherwise
    return the original name unchanged. Used by the counter so a pair is
    tracked as one shared deck pool."""
    if name is None:
        return name
    return PAIRED_CARDS.get(_normalize_sep(name), name)


# Lazy-load: derivation (天衍 / FateStrategy) pool-injection map.
# {fate_strategy_id: {canonical_name: copies}} — the cards each pool-injection
# derivation adds to the deck. These cards have 0 copies until the derivation
# is picked (parallels SIDEJOB_BONUSES). Source: tools/derivation_pool.json,
# generated from FateStrategyConfig (the game's own config).
_DERIVATION_POOL_CACHE: dict | None = None


def _derivation_pool_map() -> dict:
    global _DERIVATION_POOL_CACHE
    if _DERIVATION_POOL_CACHE is None:
        out: dict = {}
        try:
            import json as _json
            p = Path(__file__).resolve().parent / "tools" / "derivation_pool.json"
            for did, entry in _json.loads(p.read_text(encoding="utf-8")).items():
                cards = {_canonical(nm): int(cnt)
                         for nm, cnt in (entry.get("cards") or {}).items()}
                out[int(did)] = cards
        except Exception:
            out = {}
        _DERIVATION_POOL_CACHE = out
    return _DERIVATION_POOL_CACHE


class Counter:
    """Tracks how many copies of each card remain in the user's deck.

    Model (per the game's rules, confirmed by the user):
      • every card starts with DEFAULT_COPIES (8) in the deck — except
        phase-5 cards (PHASE5_COPIES = 6) and those listed in
        SPECIAL_COPIES (see above). SPECIAL_COPIES wins over phase-5.
      • DRAWING a card (dealt at round start, or the new card from a reroll)
        removes 1 copy of that card,
      • REROLLING a card away removes 3 EXTRA copies of the discarded card
        (game-rule update — was 2 in earlier patches), EXCEPT for cards in
        NO_REROLL_PENALTY which use a 0 multiplier (only the original draw
        counts; no extra burn).
    So for a normal card:
       removed[name] = draws[name] + 3 * reroll_discards[name]
    For a NO_REROLL_PENALTY card:
       removed[name] = draws[name] + 0 * reroll_discards[name]
    And remaining[name] = max(0, max_copies(name) - removed[name]).

    Draws are detected two ways:
      • reroll events (addon.reroll_events) give the discarded + drawn cards
        explicitly,
      • round-start deals show up as increases in the owned (hand+board)
        multiset between snapshots; those increases are counted as draws.
    Merges/places/absorbs only ever decrease the owned multiset, so they are
    never mistaken for draws.
    """

    def __init__(self):
        self.reset()

    def reset(self):
        self._draws = {}            # name -> copies drawn
        self._reroll_discards = {}  # name -> times rerolled away
        self._prev_owned = {}       # name -> count in hand+board at last snapshot
        # Cards the server granted "for free" (daoyun pick, 自在随心 random
        # draw, etc.) and that haven't yet shown up in the hand. When such a
        # card next appears in the hand diff, it absorbs that incoming +1 so
        # the Counter does NOT subtract it from the deck pool.
        self._pending_grants = {}   # name -> outstanding free-grant credit
        # Sidejob (副职) state. All sidejob cards start with 0 copies in the
        # deck. Picking a sidejob and breaking through realm tiers adds copies
        # via SIDEJOB_BONUSES. Non-picked sidejob cards stay at 0.
        # The pool combines copies from BOTH the primary career (picked R2)
        # AND zero-or-more secondary careers (picked via 副职兼修 fate at
        # breakthroughs). Each secondary pick is phase-filtered — only cards
        # of the pick's phase and above are granted.
        self._sidejob_pool = {}     # canonical_name -> max_copies in deck
        self._selection_applied = False
        self._applied_career_id = 0 # the primary career_id whose pool was applied
        # Each entry: {career_id, phase, applied_realm}. `applied_realm` tracks
        # which breakthrough bonuses have been applied for THIS pick — fresh
        # picks start at `phase` (the realm reached when 副职兼修 was picked).
        self._applied_secondary_picks: list = []
        self._prev_realm = 0        # last observed realm_tier (primary)
        # Derivation (天衍) pool. Like sidejob cards, derivation-only cards
        # (幻•X / 云剑•X / …) have 0 deck copies by default; picking a
        # pool-injection derivation adds its copies (DERIVATION_POOL).
        self._derivation_pool = {}   # canonical_name -> copies added by chosen derivations
        self._applied_derivations: set = set()  # FateStrategy ids already folded in

    @staticmethod
    def _is_base_deck_card(name) -> bool:
        """True for cards that belong to the base sect/sidejob deck (excludes
        dream cards and personal/fate-granted cards with id < 1_000_000)."""
        # Dream cards (梦…) are not drawn from the normal deck.
        if not name or str(name).startswith("梦"):
            return False
        # Personal / fate-granted cards (card id < 1_000_000) are not part of
        # any sect or sidejob deck — they appear in the hand via fate effects
        # or special grants and have no fixed copy count. Exclude them so the
        # counter never shows "N copies remaining" for them.
        return _canonical(_normalize_sep(str(name))) not in _personal_card_names()

    def _is_deck_card(self, name) -> bool:
        """A card is countable if it's a base deck card OR a derivation-only
        card whose pool-injection derivation the player has actually picked
        (so derivation cards stay hidden/0 until their 天衍 is chosen)."""
        if Counter._is_base_deck_card(name):
            return True
        if name and not str(name).startswith("梦"):
            return _canonical(name) in self._derivation_pool
        return False

    def _owned_multiset(self) -> dict:
        sh = shadow_state.shadow
        counts = {}
        if sh is None:
            return counts
        # Include the seasonal holding: a card parked in the seasonal zone is
        # still owned, so a hand↔seasonal round-trip must not look like a
        # removal followed by a re-draw.
        seasonal = list(getattr(sh, "seasonal", {}).values())
        for c in list(sh.hand) + list(sh.board) + seasonal:
            if c is None:
                continue
            n = getattr(c, "name", None)
            if self._is_deck_card(n):
                # Paired transform cards share a deck pool — tally both faces
                # under one canonical name (e.g. "天命•飞逝/重现").
                key = _canonical(n)
                counts[key] = counts.get(key, 0) + 1
        return counts

    def _drain_daoyun_events(self):
        """Drain free-grant events (daoyun picks, 自在随心 random draws, other
        special grants the server adds via team_container[1] during a round)
        into self._pending_grants. When a granted card next appears in the
        owned-multiset diff, the grant absorbs that incoming +1 instead of it
        being counted as a deck draw."""
        try:
            import addon
            events = addon.daoyun_grant_events
        except Exception:
            return
        while events:
            ev = events.pop(0)
            nm = ev.get("name")
            if not self._is_deck_card(nm):
                continue
            key = _canonical(nm)
            self._pending_grants[key] = self._pending_grants.get(key, 0) + 1

    def _drain_draw_events(self):
        """Drain mid-round DRAW events (addon.draw_events): a new card entered
        the hand mid-round and isn't a known grant → a real deck draw. Caught
        per-PlayerData via the team_container[1] diff, so derivation draws (云剑
        大师 / 斩道之法 / 副职大师 …) are counted even if the card is played or
        merged before the next GameStatus.

        Pre-credit `_prev_owned` for each so the GameStatus owned-multiset diff
        in observe() doesn't ALSO count the same card (same mechanism as the
        reroll-in pre-credit)."""
        try:
            import addon
            events = addon.draw_events
        except Exception:
            return
        while events:
            ev = events.pop(0)
            nm = ev.get("name")
            if not self._is_deck_card(nm):
                continue
            key = _canonical(nm)
            self._draws[key] = self._draws.get(key, 0) + 1
            self._prev_owned[key] = self._prev_owned.get(key, 0) + 1

    def _drain_reroll_events(self):
        try:
            import addon
            events = addon.reroll_events
        except Exception:
            return
        while events:
            ev = events.pop(0)
            old, new = ev.get("old"), ev.get("new")
            # When the discarded card grants a free replacement (Painter
            # 以画入道/妙笔生花/触类旁通 [置换] effect), the new card isn't
            # pulled from the deck — skip the +1 draw credit, but still
            # pre-credit `_prev_owned` so the snapshot diff doesn't catch it.
            from_free_pool = old in FREE_REPLACE_CARDS
            # Paired-card aware: tally both faces under the merged name so
            # rerolling 天命•飞逝 also burns 天命•重现 (one shared pool).
            new_key = _canonical(new)
            old_key = _canonical(old)
            if self._is_deck_card(new):
                if not from_free_pool:
                    self._draws[new_key] = self._draws.get(new_key, 0) + 1
                # Either way, the reroll-in shows up in the owned snapshot;
                # pre-credit prev_owned so the diff doesn't double-count it.
                self._prev_owned[new_key] = self._prev_owned.get(new_key, 0) + 1
            if self._is_deck_card(old):
                self._reroll_discards[old_key] = self._reroll_discards.get(old_key, 0) + 1
                # The discarded card leaves the owned set; reflect that so its
                # departure isn't later misread.
                self._prev_owned[old_key] = max(0, self._prev_owned.get(old_key, 0) - 1)

    def _apply_derivation_events(self):
        """Fold each newly-picked pool-injection derivation (天衍) into
        `_derivation_pool`. Idempotent per id via `_applied_derivations`.
        Reads `addon.chosen_derivations` (FateStrategy ids in pick order)."""
        try:
            import addon
            chosen = list(getattr(addon, "chosen_derivations", []) or [])
        except Exception:
            return
        pmap = _derivation_pool_map()
        for did in chosen:
            try:
                did = int(did)
            except (TypeError, ValueError):
                continue
            if did in self._applied_derivations:
                continue
            inj = pmap.get(did)
            if inj:
                for canon, cnt in inj.items():
                    self._derivation_pool[canon] = self._derivation_pool.get(canon, 0) + cnt
            self._applied_derivations.add(did)

    def _apply_sidejob_events(self, state):
        """Detect sidejob selection (primary + each 副职兼修 secondary) and
        realm-tier breakthroughs; populate `_sidejob_pool` with the
        appropriate copies. Each trigger fires at most once per Counter
        lifetime (reset by `reset()`).

        副职兼修 rules:
          • The fate can be picked at multiple breakthroughs (phase 2, 3,
            4, 5). Each pick grants an additional sidejob deck.
          • Only cards of the pick's phase and above are granted (so
            picking at phase 2 skips realm-1 starter cards).
          • If a granted sidejob has SIDEJOB_BONUSES (currently only
            炼丹师 / Elixirist), realm-tier breakthroughs AFTER the pick
            still apply those bonuses to this secondary deck.
        """
        try:
            import shadow_state as _ss
            career_id = _ss.get_career_pick()
            secondary_picks = _ss.get_secondary_career_picks()
        except Exception:
            career_id = 0
            secondary_picks = []
        if not career_id:
            return
        prefix = CAREER_TO_SIDEJOB_PREFIX.get(career_id)
        if not prefix:
            return
        bonuses = SIDEJOB_BONUSES.get(prefix, {})

        # ── Primary selection ────────────────────────────────────────────
        # Fires once when SelectCareerReq is first observed. Also re-fires
        # if the career CHANGES (e.g. between games in the same consumer-
        # thread lifetime, or if the user genuinely switches mid-game).
        # Clears the old pool first.
        if not self._selection_applied or self._applied_career_id != career_id:
            if self._selection_applied and self._applied_career_id != career_id:
                self._sidejob_pool = {}
                self._applied_secondary_picks = []
                self._prev_realm = 0
            base_pool = _sidejob_default_pool(prefix)
            overrides = bonuses.get("selection_overrides") or {}
            for nm, cnt in overrides.items():
                base_pool[nm] = cnt
            for nm, cnt in base_pool.items():
                self._sidejob_pool[nm] = self._sidejob_pool.get(nm, 0) + cnt
            self._selection_applied = True
            self._applied_career_id = career_id

        # ── Current realm (used by primary AND secondary breakthroughs) ──
        # Read from the LIVE shadow first — PlayerData updates shadow.realm_tier
        # mid-round when a breakthrough happens, but the cached GameState
        # we get here still has the old realm from the last GameStatus.
        cur_realm = 0
        sh = shadow_state.shadow
        if sh is not None:
            cur_realm = int(getattr(sh, "realm_tier", 0) or 0)
        if cur_realm == 0 and state is not None:
            me_idx = getattr(state, "me_index", -1)
            players = getattr(state, "players", [])
            if 0 <= me_idx < len(players):
                cur_realm = int(getattr(players[me_idx], "realm_tier", 0) or 0)

        # ── 副职兼修 secondary picks ─────────────────────────────────────
        # Each pick from shadow_state may be new (apply initial pool now) or
        # already-applied (carry forward to handle realm-bonus catch-up).
        # Identity = (career_id, phase). The same career picked at different
        # phases is two different picks (each grants its own deck).
        applied_keys = {(p["career_id"], p["phase"])
                        for p in self._applied_secondary_picks}
        for pick in secondary_picks:
            key = (int(pick.get("career_id", 0)),
                   int(pick.get("phase", 2)))
            if key in applied_keys:
                continue
            sec_cid, sec_phase = key
            sec_prefix = CAREER_TO_SIDEJOB_PREFIX.get(sec_cid)
            if not sec_prefix:
                continue
            # Initial pool — phase-filtered (only phase >= sec_phase cards).
            sec_pool = _sidejob_pool_filtered(sec_prefix, min_phase=sec_phase)
            sec_bonuses = SIDEJOB_BONUSES.get(sec_prefix, {})
            sec_overrides = sec_bonuses.get("selection_overrides") or {}
            for nm, cnt in sec_overrides.items():
                # Apply override only if the card passed the phase filter
                # (i.e. it's already in sec_pool). Skip cards below pick phase.
                key_c = _canonical(nm)
                if key_c in sec_pool:
                    sec_pool[key_c] = cnt
            for nm, cnt in sec_pool.items():
                self._sidejob_pool[nm] = self._sidejob_pool.get(nm, 0) + cnt
            # Record so we don't re-apply, and so realm bonuses catch up.
            # `applied_realm` = sec_phase because picking at phase N means the
            # realm is already N (just transitioned); breakthroughs N+1 etc.
            # are the only ones we need to apply going forward.
            self._applied_secondary_picks.append({
                "career_id": sec_cid,
                "phase": sec_phase,
                "applied_realm": sec_phase,
            })

        # ── Realm-tier breakthroughs ─────────────────────────────────────
        # Primary: bonuses defined under primary career's SIDEJOB_BONUSES.
        if cur_realm > self._prev_realm:
            for r in range(self._prev_realm + 1, cur_realm + 1):
                key = f"realm_{r - 1}_to_{r}"
                for nm, cnt in (bonuses.get(key) or {}).items():
                    self._sidejob_pool[nm] = self._sidejob_pool.get(nm, 0) + cnt
            self._prev_realm = cur_realm
        # Each secondary pick: same logic against its own career's bonuses.
        # `applied_realm` advances independently per pick (since they were
        # added at different breakthrough phases).
        for entry in self._applied_secondary_picks:
            sec_prefix = CAREER_TO_SIDEJOB_PREFIX.get(entry["career_id"])
            if not sec_prefix:
                continue
            sec_bonuses = SIDEJOB_BONUSES.get(sec_prefix, {})
            sec_applied = int(entry.get("applied_realm", entry["phase"]))
            if cur_realm > sec_applied:
                for r in range(sec_applied + 1, cur_realm + 1):
                    key = f"realm_{r - 1}_to_{r}"
                    for nm, cnt in (sec_bonuses.get(key) or {}).items():
                        self._sidejob_pool[nm] = self._sidejob_pool.get(nm, 0) + cnt
                entry["applied_realm"] = cur_realm

    def observe(self, state):
        self._drain_reroll_events()
        self._drain_daoyun_events()
        self._drain_draw_events()
        self._apply_sidejob_events(state)
        self._apply_derivation_events()
        owned = self._owned_multiset()
        # Any net increase in owned copies (not from a reroll-in or a free
        # grant) is a deal/draw. Free grants (daoyun, 自在随心, etc.) sit in
        # _pending_grants and absorb incoming +1s without decrementing the
        # deck pool.
        for name, cnt in owned.items():
            prev = self._prev_owned.get(name, 0)
            if cnt > prev:
                diff = cnt - prev
                grant_credit = min(diff, self._pending_grants.get(name, 0))
                if grant_credit:
                    self._pending_grants[name] -= grant_credit
                    if self._pending_grants[name] <= 0:
                        del self._pending_grants[name]
                actual_draws = diff - grant_credit
                if actual_draws:
                    self._draws[name] = self._draws.get(name, 0) + actual_draws
        # Snapshot becomes the new baseline (decreases = merges/places/absorbs).
        self._prev_owned = owned

    def remaining(self) -> dict:
        # Show every card SEEN this game — held in hand/seasonal, sitting on the
        # board, OR drawn earlier and since played/absorbed. A real 记牌器 needs
        # to answer "how many of card X are left in my deck" even when X isn't
        # currently in hand, so we no longer restrict the list to held cards.
        # (The per-card _draws/_reroll_discards tallies make every count exact.)
        sh = shadow_state.shadow
        held = set()
        in_hand = set()   # cards you currently hold in hand — shown even at 0 left
        if sh is not None:
            # cards currently in hand or the seasonal (织梦) holding
            for c in list(sh.hand) + list(getattr(sh, "seasonal", {}).values()):
                if c is not None and self._is_deck_card(getattr(c, "name", None)):
                    key = _canonical(c.name)
                    held.add(key)
                    in_hand.add(key)
            # cards currently placed on the board
            for c in list(sh.board):
                if c is not None and self._is_deck_card(getattr(c, "name", None)):
                    held.add(_canonical(c.name))
        # every card ever drawn this game (keys are already canonical) — this is
        # what surfaces cards you've drawn and then played/absorbed.
        for nm in self._draws:
            if self._is_deck_card(nm):
                held.add(nm)
        out = {}
        phase_map = _name_to_phase()
        sidejob_prefix_map = _name_to_sidejob_prefix()
        # Which sidejobs the player picked. Both primary (initial R2 pick) and
        # ALL 副职兼修 secondary picks contribute to the legal-sidejob set.
        try:
            import shadow_state as _ss
            picked_career = _ss.get_career_pick()
            sec_picks = _ss.get_secondary_career_picks()
        except Exception:
            picked_career = 0
            sec_picks = []
        picked_sidejob_prefixes = set()
        primary_prefix = CAREER_TO_SIDEJOB_PREFIX.get(picked_career, 0)
        if primary_prefix:
            picked_sidejob_prefixes.add(primary_prefix)
        for sp in sec_picks:
            sp_prefix = CAREER_TO_SIDEJOB_PREFIX.get(sp.get("career_id", 0), 0)
            if sp_prefix:
                picked_sidejob_prefixes.add(sp_prefix)

        for name in held:
            # Look up sidejob prefix under the face name (paired cards aren't
            # sidejob cards, but cover both forms defensively).
            face_for_lookup = _normalize_sep(_PAIR_CANONICAL_TO_FACE.get(name, name))
            sidejob_prefix = sidejob_prefix_map.get(face_for_lookup)

            if not Counter._is_base_deck_card(name):
                # Derivation-only card (幻•X / 云剑•X / …): 0 in the base deck;
                # every copy comes from a picked pool-injection 天衍 (added below).
                max_copies = 0
            elif sidejob_prefix in SIDEJOB_PREFIXES:
                # Side-job card. Pool is 0 unless this is one of the picked
                # sidejobs (primary OR secondary via 副职兼修) AND the card
                # has had bonuses applied.
                if sidejob_prefix not in picked_sidejob_prefixes:
                    max_copies = 0
                else:
                    max_copies = self._sidejob_pool.get(name, 0)
            else:
                # Main-sect / special / fate card — existing rules apply.
                phase_lookup_name = face_for_lookup
                if name in SPECIAL_COPIES:
                    max_copies = SPECIAL_COPIES[name]
                elif phase_map.get(phase_lookup_name) == 5:
                    max_copies = PHASE5_COPIES
                else:
                    max_copies = DEFAULT_COPIES

            # 天衍 pool-injection: picked derivations add copies on top (covers
            # both derivation-only cards and dual sect/sidejob cards a 天衍 boosts).
            max_copies += self._derivation_pool.get(name, 0)

            reroll_mult = 0 if name in NO_REROLL_PENALTY else 3
            removed = (
                self._draws.get(name, 0)
                + reroll_mult * self._reroll_discards.get(name, 0)
            )
            left = max(0, max_copies - removed)
            # Exhausted cards (0 left in deck) drop off the list — no point
            # showing a card you can no longer draw — UNLESS you're currently
            # holding one in hand, in which case keep it visible at 0 so you can
            # see you have it but can't draw any more.
            if left > 0 or name in in_hand:
                out[name] = left
        return out
