"""
proxy_view.py
─────────────
Turns a parsed GameState (+ the client-side shadow) into the JSON view-model
the UI consumes. Also hosts the card Counter (deck-tracking) — a stub here,
filled in at milestone M4.

Imported by runtime.start_consumer after proxy/ is on sys.path, so the
top-level `import shadow_state` resolves to the same singleton the addon uses.
"""
import json
import sys
from pathlib import Path

import shadow_state
# R28: optional local BattleLog.json fallback for HP / tipo / maxTipo.
# The wire doesn't carry these as direct integers; the game client writes
# them to a JSON file we can tail. Best-effort import — if the module fails
# to load we just skip the override.
try:
    import battle_log as _battle_log
except Exception:
    _battle_log = None

# Fate id → yi-sim talent metadata (generated by build_fate_map.py).
_FATE_MAP_PATH = Path(__file__).resolve().parent / "proxy" / "fate_talent_map.json"
_fate_map_cache = None
_unmapped_warned: set = set()


def _fate_map() -> dict:
    global _fate_map_cache
    if _fate_map_cache is None:
        try:
            _fate_map_cache = json.loads(_FATE_MAP_PATH.read_text(encoding="utf-8"))
        except Exception:
            _fate_map_cache = {}
    return _fate_map_cache


def _resolve_fate_meta(fmap: dict, fid: int, phase: int):
    """Look up a fate's talent metadata, picking the right phase variant.

    Backward-compat: today every fate_talent_map.json entry is single-variant
    (phase-agnostic). If a future entry adds `phases: {"1": {...}, "2": {...}}`,
    we merge the matching phase's overrides over the base entry. If the entry
    has no `phases` key the base entry is returned unchanged.
    Returns None when the id is unmapped.
    """
    base = fmap.get(str(fid))
    if not base:
        return None
    phases = base.get("phases") if isinstance(base, dict) else None
    if not isinstance(phases, dict):
        return base
    override = phases.get(str(phase)) or phases.get(int(phase) if isinstance(phase, int) else None)
    if isinstance(override, dict):
        merged = dict(base)
        merged.update(override)
        # `phases` itself isn't useful downstream — drop it.
        merged.pop("phases", None)
        return merged
    return base


def _warn_unmapped_fate(fid: int) -> None:
    """Log a one-shot warning (per process) when a fate id is missing from the
    talent map. The fate still surfaces in `fateNames` for display — we just
    can't model it in the damage sim yet."""
    if fid in _unmapped_warned:
        return
    _unmapped_warned.add(fid)
    try:
        name = shadow_state.fate_name(fid)
    except Exception:
        name = "?"
    print(f"[fate] unmapped id={fid} ({name}) — add to fate_talent_map.json to model in sim",
          file=sys.stderr, flush=True)


def _fates_to_talents(fate_ids):
    """Convert a list of fate ids (in PICK ORDER) into (talents, names).

    Each entry's index in the list = phase (1-indexed). The phase is stored
    both as the existing `position` field (yisim uses it to resolve any
    `{n}` placeholder in `runtimeKey`) AND as a new `phase` field on the
    talent object so the UI and any future phase-aware lookup can use it.
    Unmapped ids still surface in `names` but are skipped in `talents`,
    and a one-shot console warning fires per unique unmapped id.

    talents match the shape yisim.simulate expects via normalizeTalents:
      {detected, position, phase, name, simulationKind, runtimeKey,
       grantedCardBaseIds}

    Phase variants seam: if a future fate_talent_map.json entry adds
    `phases: { "2": { ... }, "3": { ... } }`, `_resolve_fate_meta` will
    apply the right override automatically — no caller change needed.
    """
    fmap = _fate_map()
    talents, names = [], []
    for i, fid in enumerate(fate_ids or []):
        try:
            fid_i = int(fid)
        except (TypeError, ValueError):
            continue
        phase = i + 1
        names.append(shadow_state.fate_name(fid_i))
        meta = _resolve_fate_meta(fmap, fid_i, phase)
        if not meta:
            _warn_unmapped_fate(fid_i)
            continue
        talents.append({
            "detected": True,
            "position": phase,
            "phase": phase,
            "name": meta.get("name", ""),
            "simulationKind": meta.get("simulationKind", "non-combat-or-unsupported"),
            "runtimeKey": meta.get("runtimeKey"),
            "grantedCardBaseIds": meta.get("grantedCardBaseIds") or [],
        })
    return talents, names


def _build_fates():
    """Back-compat shim: ME's fates from addon.chosen_fates → (talents, names)."""
    try:
        import addon
        ids = list(addon.chosen_fates)
    except Exception:
        ids = []
    return _fates_to_talents(ids)


def _card(c):
    """ZoneCard | CardState | None → {name, level} | None."""
    if c is None:
        return None
    return {"name": getattr(c, "name", "?"), "level": int(getattr(c, "level", 1) or 1)}


def _board_list(board, unlocked):
    out = []
    for i in range(shadow_state.BOARD_SLOTS):
        c = board[i] if board and i < len(board) else None
        out.append(_card(c))
    return out


class OpponentTracker:
    """Remembers each player's board per round so the matchup can use the
    opponent's board from a PREVIOUS round — in-game you never see an
    opponent's current-round board, only what they last fought with.
    """

    def __init__(self):
        self.reset()

    def reset(self):
        self._by_round = {}   # round_num -> {player_id: [card-dict|None, ...]}

    def observe(self, state):
        r = state.round_num
        slot = self._by_round.setdefault(r, {})
        for p in state.players:
            slot[p.player_id] = [_card(c) for c in (p.board or [])]
        # Keep memory bounded.
        if len(self._by_round) > 4:
            for old in sorted(self._by_round)[:-4]:
                self._by_round.pop(old, None)

    def last_seen(self, player_id, current_round):
        """The opponent's board from the most recent round before this one.
        Returns (board, from_round) or (None, None)."""
        rounds = sorted(rr for rr in self._by_round if rr < current_round)
        for rr in reversed(rounds):
            board = self._by_round[rr].get(player_id)
            if board and any(board):
                return board, rr
        return None, None

    def previous_round(self, player_id, current_round):
        """The opponent's board strictly from `current_round - 1`.

        Use this for the matchup panel — "what the current opponent had last
        round" — instead of `last_seen`, which can drift many rounds back if
        the opponent has been quiet. Falls back to `last_seen` if the previous
        round is missing (e.g. very first round we observed them).
        """
        slot = self._by_round.get(current_round - 1, {})
        board = slot.get(player_id)
        if board and any(board):
            return board, current_round - 1
        return self.last_seen(player_id, current_round)


def _pick_opponent(state):
    """Choose the opponent to display/simulate against.

    Preference order:
      1. **The next-round opponent** — `state.players[me].next_opponent_id` (the
         UID broadcast on the user's player struct, field 9). YiXianPai pairs you
         with a DIFFERENT opponent each round, so this is what the user is about
         to fight; not the same as the previously-fought opponent.
      2. The player the user most recently fought (`addon.my_last_opponent`)
         — fallback for round 1 / states where field 9 was missing.
      3. The live opponent with the most cards on board.
      4. The first non-me player.
    Returns a PlayerState or None.
    """
    if not state.players:
        return None
    me_idx = state.me_index
    others = [(i, p) for i, p in enumerate(state.players) if i != me_idx]
    if not others:
        return None

    # 1. Next-round matchup from the broadcast.
    next_uid = ""
    if 0 <= me_idx < len(state.players):
        next_uid = getattr(state.players[me_idx], "next_opponent_id", "") or ""
    if next_uid:
        for _, p in others:
            if p.player_id == next_uid:
                return p

    # 2. Fallback: most recently fought opponent (`my_last_opponent`).
    try:
        import addon
        target_uid = addon.my_last_opponent
    except Exception:
        target_uid = ""
    if target_uid:
        for _, p in others:
            if p.player_id == target_uid and p.destiny > 0:
                return p
    # Most board cards among still-alive opponents.
    alive = [(i, p) for i, p in others if p.destiny > 0] or others
    alive.sort(key=lambda ip: sum(1 for c in (ip[1].board or []) if c), reverse=True)
    return alive[0][1]


def _battle_log_stats(round_num: int, display_name: str):
    """Look up `(life, xiuwei, tipo, max_tipo, max_hp, realm_tier,
    from_round)` from BattleLog.json for the given player display name.

    Returns None if the log isn't available, the module didn't import, the
    display name is missing, or no entry exists. The log is the only
    authoritative source for `max_hp`, `tipo`, and `max_tipo` — the wire
    protocol doesn't carry them directly. Callers should fall back to
    wire-derived values when this returns None.
    """
    if _battle_log is None or not display_name:
        return None
    try:
        return _battle_log.get_reader().extract_stats(round_num, display_name)
    except Exception:
        return None


def build_view_model(state, counter=None, last_battle=None, opp_tracker=None):
    sh = shadow_state.shadow
    unlocked = shadow_state.unlocked_board_slots(state.round_num)

    vm = {
        "round": state.round_num,
        "phase": state.phase,
        "me": None,
        "opponent": None,
        "counter": {"remaining": counter.remaining() if counter else {}},
    }

    # ── You ──────────────────────────────────────────────────────────────────
    if state.me_index >= 0 and state.me_index < len(state.players):
        me = state.players[state.me_index]
        if sh is not None:
            hand = [_card(c) for c in sh.hand if c is not None]
            board = _board_list(sh.board, unlocked)
            xiuwei, tipo, realm = sh.xiuwei, sh.tipo, sh.realm_tier
            rerolls = sh.rerolls
            seasonal = [_card(c) for c in sh.seasonal.values() if c is not None]
        else:
            hand = [_card(c) for c in me.cards]
            board = _board_list(me.board, unlocked)
            xiuwei, tipo, realm = me.xiuwei, me.tipo, me.realm_tier
            rerolls = getattr(me, "rerolls", 0)
            seasonal = []
        # R28: prefer BattleLog.json for HP / tipo / maxTipo when available.
        # The log is slightly delayed but authoritative (the game client
        # writes the exact displayed values). Wire-derived stays as the
        # fallback when the log lacks an entry for this round.
        log_stats = _battle_log_stats(state.round_num, getattr(me, "display_name", ""))
        log_hp     = int(log_stats["max_hp"])     if log_stats else 0
        log_tipo   = int(log_stats["tipo"])       if log_stats else None
        log_maxtp  = int(log_stats["max_tipo"])   if log_stats else 0
        log_round  = int(log_stats["from_round"]) if log_stats else None

        hp_val   = log_hp if log_hp > 0 else me.hp
        tipo_val = log_tipo if log_tipo is not None else tipo
        max_tipo = log_maxtp  # 0 if log missing — UI treats 0 as "unknown"

        avail, thr, gate = shadow_state.breakthrough_status(realm, xiuwei, tipo_val)
        fates, fate_names = _build_fates()
        # R27 diagnostic kept side-by-side so we can still see all candidates
        # in the console probe. `me.hp` for UI / sim consumers now resolves
        # via the precedence above (BattleLog > wire formula).
        me_field5 = int(getattr(me, "hp_field", 0) or 0)
        vm["me"] = {
            "destiny": me.destiny, "hp": hp_val,
            "hpFromXiuwei": 40 + xiuwei,
            "hpFromField5": 40 + me_field5,
            "hpFromLog": log_hp,
            "tipoFromLog": (log_tipo if log_tipo is not None else 0),
            "maxTipoFromLog": log_maxtp,
            "logFromRound": log_round,
            "xiuwei": xiuwei, "tipo": tipo_val, "max_tipo": max_tipo,
            "realm_tier": realm,
            "rerolls": rerolls,
            "unlocked": unlocked,
            "hand": hand, "board": board,
            "seasonal": seasonal,
            "fates": fates, "fateNames": fate_names,
            "breakthrough": {"available": bool(avail), "threshold": thr, "gate": gate},
        }

    # ── Opponent (matchup target) ──────────────────────────────────────────────
    # Round 14: use opp.board DIRECTLY — it's the current-round board, parsed
    # from f200.6 on each player struct in the latest GameStatus. The server
    # broadcasts every player's board at the start of each round; that's the
    # roster the opponent will fight us with this round (boards lock between
    # rounds). OpponentTracker still observes for history, but we don't pull
    # the displayed board from it anymore.
    opp = _pick_opponent(state)
    if opp is not None:
        board = [_card(c) for c in (opp.board or [])]
        from_round = state.round_num
        # Pad/truncate to 8 slots.
        board = (board + [None] * shadow_state.BOARD_SLOTS)[:shadow_state.BOARD_SLOTS]
        # R26: opponent fates decoded from f200["5"] (packed varint list, R24
        # Phase B addendum 8) flow through the SAME pipeline as me's fates —
        # `_fates_to_talents` builds talent objects with `phase = pick order`
        # so the matchup-mode sim can apply them via opts.opponentTalents.
        opp_fates, opp_fate_names = _fates_to_talents(getattr(opp, "fates", []) or [])
        # R27: same HP diagnostic for the displayed opponent.
        opp_field5 = int(getattr(opp, "hp_field", 0) or 0)
        # R28: BattleLog override for opponent too (same precedence as ME).
        opp_log = _battle_log_stats(state.round_num, getattr(opp, "display_name", ""))
        opp_log_hp    = int(opp_log["max_hp"])     if opp_log else 0
        opp_log_tipo  = int(opp_log["tipo"])       if opp_log else None
        opp_log_maxtp = int(opp_log["max_tipo"])   if opp_log else 0
        opp_hp_val    = opp_log_hp if opp_log_hp > 0 else opp.hp
        opp_tipo_val  = opp_log_tipo if opp_log_tipo is not None else opp.tipo
        vm["opponent"] = {
            "player_id": opp.player_id,
            "character": "",  # opponents' class isn't directly exposed
            "destiny": opp.destiny, "hp": opp_hp_val,
            "hpFromXiuwei": 40 + opp.xiuwei,
            "hpFromField5": 40 + opp_field5,
            "hpFromLog": opp_log_hp,
            "tipoFromLog": (opp_log_tipo if opp_log_tipo is not None else 0),
            "maxTipoFromLog": opp_log_maxtp,
            "xiuwei": opp.xiuwei, "tipo": opp_tipo_val, "max_tipo": opp_log_maxtp,
            "realm_tier": opp.realm_tier,
            "phase": state.phase,
            "unlocked": unlocked,
            "board": board,
            "boardFromRound": from_round,
            "fates": opp_fates, "fateNames": opp_fate_names,
        }

    # R27: one-shot per-frame console probe so the user can read both
    # candidates without opening devtools. Prints ME plus every visible
    # player at GameStatus arrival — gated to `prep` to avoid duplicate
    # log lines during the battle phase.
    if state.phase == "prep":
        _hp_probe(state)

    return vm


_hp_probe_seen: set = set()


def _hp_probe(state) -> None:
    """Print per-player `(xiuwei, hp_field, 40+xiuwei, 40+hp_field)` once per
    (round, me-uid) pair. R27 diagnostic — remove once HP source is locked in.
    """
    me_uid = ""
    if 0 <= state.me_index < len(state.players):
        me_uid = state.players[state.me_index].player_id
    key = (state.round_num, me_uid)
    if key in _hp_probe_seen:
        return
    _hp_probe_seen.add(key)
    import sys
    for p in state.players:
        tag = "ME " if p.player_id == me_uid else "   "
        f5 = int(getattr(p, "hp_field", 0) or 0)
        print(f"[hp-probe] R{state.round_num} {tag}{p.player_id[:24]:24s} "
              f"xiuwei={p.xiuwei:3d} field5={f5:3d}  "
              f"hp(xw)={40 + p.xiuwei:3d} hp(f5)={40 + f5:3d}",
              file=sys.stderr, flush=True)


DEFAULT_COPIES = 8  # each card has 8 copies in the deck unless specified
PHASE5_COPIES = 6   # phase-5 (latest-patch) cards: 6 copies instead of 8

# Cards with non-default deck size. Add new entries here as we learn them.
# Takes precedence over the phase-5 rule (e.g. 悟道丹 stays at 3 even though
# its CardConfig phase may be > 1).
SPECIAL_COPIES = {
    "洗髓丹":  3,   # Marrow-Cleansing Pill — Elixirist dan, 3 copies
    "悟道丹":  3,   # Enlightenment Pill — Elixirist dan, 3 copies
    "锻体玄丹": 3,  # Body-Forging Mystic Pill — Elixirist dan, 3 copies
}


# Lazy-load card-name → phase mapping from tools/card_phases.json (extracted
# from CardConfig.xlsx via tools/extract_card_phases.py). Used to identify
# phase-5 cards for the reroll-copies rule.
_PHASE_MAP_FILE = Path(__file__).resolve().parent / "tools" / "card_phases.json"
_phase_map_cache: dict | None = None


def _name_to_phase() -> dict:
    """Return {card_name: highest_observed_phase}. Cached.

    Some names appear under multiple ids (e.g. base + leveled forms or
    cross-references); we keep the highest phase value seen, which biases
    toward the newer / more-restrictive rule.
    """
    global _phase_map_cache
    if _phase_map_cache is not None:
        return _phase_map_cache
    out: dict[str, int] = {}
    try:
        with _PHASE_MAP_FILE.open(encoding="utf-8") as f:
            data = json.load(f)
        for info in data.values():
            nm = info.get("name", "")
            ph = int(info.get("phase", 0) or 0)
            if not nm:
                continue
            if ph > out.get(nm, 0):
                out[nm] = ph
    except Exception:
        # Missing or unreadable file → return empty map; remaining() falls
        # back to DEFAULT_COPIES for everything (pre-phase-5 behavior).
        out = {}
    _phase_map_cache = out
    return out

# Cards exempt from the +3 reroll-burn penalty. Rerolling these away still
# costs the 1 copy that was originally drawn, but the game does NOT burn the
# extra 3 copies from the deck. (Confirmed game-rule for Painter side-job
# class spells that are part of a limited grant pool, not the regular deck.)
NO_REROLL_PENALTY = {
    "练笔",      # Sketch
    "以画入道",  # Painting as Dao
    "妙笔生花",  # Magic Brush Flowers
    "触类旁通",  # Inferring from one to others
}

# Cards whose REROLL grants a replacement that ISN'T pulled from the deck.
# When the player rerolls one of these away, the NEW card that appears in
# the slot is drawn from a special grant pool (e.g. Painter [置换] picks),
# so it does NOT consume a deck copy of itself. We skip the +1 draw
# credit for the replacement in `_drain_reroll_events`.
FREE_REPLACE_CARDS = {
    "以画入道",  # Painting as Dao
    "妙笔生花",  # Magic Brush Flowers
    "触类旁通",  # Inferring from one to others
}


class Counter:
    """Tracks how many copies of each card remain in the user's deck.

    Model (per the game's rules, confirmed by the user):
      • every card starts with DEFAULT_COPIES (8) in the deck — except
        phase-5 cards (PHASE5_COPIES = 6) and those listed in
        SPECIAL_COPIES (see above). SPECIAL_COPIES wins over phase-5.
      • DRAWING a card (dealt at round start, or the new card from a reroll)
        removes 1 copy of that card,
      • REROLLING a card away removes 3 EXTRA copies of the discarded card
        (game-rule update — was 2 in earlier patches), EXCEPT for cards in
        NO_REROLL_PENALTY which use a 0 multiplier (only the original draw
        counts; no extra burn).
    So for a normal card:
       removed[name] = draws[name] + 3 * reroll_discards[name]
    For a NO_REROLL_PENALTY card:
       removed[name] = draws[name] + 0 * reroll_discards[name]
    And remaining[name] = max(0, max_copies(name) - removed[name]).

    Draws are detected two ways:
      • reroll events (addon.reroll_events) give the discarded + drawn cards
        explicitly,
      • round-start deals show up as increases in the owned (hand+board)
        multiset between snapshots; those increases are counted as draws.
    Merges/places/absorbs only ever decrease the owned multiset, so they are
    never mistaken for draws.
    """

    def __init__(self):
        self.reset()

    def reset(self):
        self._draws = {}            # name -> copies drawn
        self._reroll_discards = {}  # name -> times rerolled away
        self._prev_owned = {}       # name -> count in hand+board at last snapshot

    @staticmethod
    def _is_deck_card(name) -> bool:
        # Dream cards (梦…) are not drawn from the normal deck.
        return bool(name) and not str(name).startswith("梦")

    def _owned_multiset(self) -> dict:
        sh = shadow_state.shadow
        counts = {}
        if sh is None:
            return counts
        # Include the seasonal holding: a card parked in the seasonal zone is
        # still owned, so a hand↔seasonal round-trip must not look like a
        # removal followed by a re-draw.
        seasonal = list(getattr(sh, "seasonal", {}).values())
        for c in list(sh.hand) + list(sh.board) + seasonal:
            if c is None:
                continue
            n = getattr(c, "name", None)
            if self._is_deck_card(n):
                counts[n] = counts.get(n, 0) + 1
        return counts

    def _drain_reroll_events(self):
        try:
            import addon
            events = addon.reroll_events
        except Exception:
            return
        while events:
            ev = events.pop(0)
            old, new = ev.get("old"), ev.get("new")
            # When the discarded card grants a free replacement (Painter
            # 以画入道/妙笔生花/触类旁通 [置换] effect), the new card isn't
            # pulled from the deck — skip the +1 draw credit, but still
            # pre-credit `_prev_owned` so the snapshot diff doesn't catch it.
            from_free_pool = old in FREE_REPLACE_CARDS
            if self._is_deck_card(new):
                if not from_free_pool:
                    self._draws[new] = self._draws.get(new, 0) + 1
                # Either way, the reroll-in shows up in the owned snapshot;
                # pre-credit prev_owned so the diff doesn't double-count it.
                self._prev_owned[new] = self._prev_owned.get(new, 0) + 1
            if self._is_deck_card(old):
                self._reroll_discards[old] = self._reroll_discards.get(old, 0) + 1
                # The discarded card leaves the owned set; reflect that so its
                # departure isn't later misread.
                self._prev_owned[old] = max(0, self._prev_owned.get(old, 0) - 1)

    def observe(self, state):
        self._drain_reroll_events()
        owned = self._owned_multiset()
        # Any net increase in owned copies (not from a reroll-in) is a deal/draw.
        for name, cnt in owned.items():
            prev = self._prev_owned.get(name, 0)
            if cnt > prev:
                self._draws[name] = self._draws.get(name, 0) + (cnt - prev)
        # Snapshot becomes the new baseline (decreases = merges/places/absorbs).
        self._prev_owned = owned

    def remaining(self) -> dict:
        # Round 12: only show cards currently held in hand or seasonal — once a
        # card is fully placed/absorbed it shouldn't clog the counter list.
        # If the user re-draws a copy later, it reappears with its accurate
        # remaining count (the internal _draws/_reroll_discards tallies persist).
        sh = shadow_state.shadow
        held = set()
        if sh is not None:
            for c in list(sh.hand) + list(getattr(sh, "seasonal", {}).values()):
                if c is not None and self._is_deck_card(getattr(c, "name", None)):
                    held.add(c.name)
        out = {}
        phase_map = _name_to_phase()
        for name in held:
            # SPECIAL_COPIES wins (e.g. 悟道丹 stays at 3). Otherwise,
            # phase-5 cards start with 6 copies; everything else with 8.
            if name in SPECIAL_COPIES:
                max_copies = SPECIAL_COPIES[name]
            elif phase_map.get(name) == 5:
                max_copies = PHASE5_COPIES
            else:
                max_copies = DEFAULT_COPIES
            reroll_mult = 0 if name in NO_REROLL_PENALTY else 3
            removed = (
                self._draws.get(name, 0)
                + reroll_mult * self._reroll_discards.get(name, 0)
            )
            out[name] = max(0, max_copies - removed)
        return out
